### ISSUE TITLE
Gene Expression Databases release v3.0.0 

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/Gene-Expression-Databases#1]
Dear @msevestre, @JLPangloss, @RBurghaus, @Yuri05,

Recently our articel "Gene Expression Databases for PBPK modeling of humans & animal species" was accepted in  CPT: Pharmacometrics & Systems Pharmacology.

As part of the SI material the R code for establishing the gene expression data bases for 17 species was published. 

I uploaded the code and the resulting databases for PK-Sim into a [new release (3.0.0) of this repository](https://github.com/Open-Systems-Pharmacology/Gene-Expression-Databases/releases/tag/v3.0.0) 

Feel free to check out the code, I'm mentally prepared for all the bugs that might turn up :-D 
Let me know if something is unclear or does not work properly. 

I would like to post this also in the main forum, as soon as the public link to the article is available. 

Best
Henrik

**Comment by HenrikCordes** [comment]
Hi @Yuri05,

I tried to set up the pre-release as discussed. The link to the acceped article is currently missing, everything else should be set up accordingly. 

Let me know if something needs to be changed or done.

Best
Henrik

**Comment by Yuri05** [comment]
Hi Henrik,

looks good. I just created a Pull Request from the new branch into the master. 
Once this PR is merged, the changes (R-Code etc.) will be integrated into the main brnach of the repo.
